const iceCreamFlavors=[]
iceCreamFlavors.push('Vanila')
console.log(iceCreamFlavors)
iceCreamFlavors.push('Strawberry')
console.log(iceCreamFlavors)
iceCreamFlavors.push('Chocalate')
console.log(iceCreamFlavors)
iceCreamFlavors.push('Cooki and cream')
console.log(iceCreamFlavors)
iceCreamFlavors.push('Mango')
console.log(iceCreamFlavors)
iceCreamFlavors.push('Pienepple')
console.log(iceCreamFlavors)
iceCreamFlavors.push('Pista')
console.log(iceCreamFlavors)
iceCreamFlavors.push('Black current')
console.log(iceCreamFlavors)
iceCreamFlavors.push('Almond')
console.log(iceCreamFlavors)
iceCreamFlavors.push('Pista and Almond')
console.log(iceCreamFlavors)